#!/bin/bash

read -p "Enter files to add: " files_to_add
read -p "Enter commit message: " commit_message

if [ -z "$commit_message" ]; then
  echo "Commit message cannot be empty."
  exit 1
fi
#Status before
git status
# Add the specified files to the staging area
git add $files_to_add
# Status after
git status
# Commit with the provided message
git commit -m "$commit_message"

echo "Changes committed with message: $commit_message"

